#undef TAPPING_TERM

#define TAPPING_TERM 150
#define COMBO_TERM 35
#define COMBO_COUNT 5
#define TAPPING_TERM_PER_KEY
#define CHORDAL_HOLD
#define LAYER_STATE_8BIT
#define RGB_MATRIX_STARTUP_SPD 60

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 50

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 3

