#pragma once

#define MASTER_LEFT
#define TAPPING_TERM 165
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define COMBO_TERM 35

#ifdef RGBLIGHT_ENABLE
    #define RGBLIGHT_LIMIT_VAL 120
    #define RGBLIGHT_HUE_STEP 10
    #define RGBLIGHT_SAT_STEP 17
    #define RGBLIGHT_VAL_STEP 17
#endif
